# Generated by Django 6.0.1 on 2026-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ike_id', models.CharField(max_length=255)),
                ('vpn_subnet', models.CharField(max_length=64)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
